---
provisioner:
  name: chef_solo

suites:
  - name: default
    run_list:
      - recipe[glusterfs::default]
  - name: version
    run_list:
      - recipe[glusterfs::default]
    attributes:
      glusterfs:
        version: 3.4
  - name: server
    run_list:
      - recipe[glusterfs::server]
