---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[glusterfs::default]
  - name: version
    run_list:
      - recipe[glusterfs::default]
    attributes:
      glusterfs:
        version: 3.4
