name             'glusterfs'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures glusterfs'
long_description 'Installs/Configures glusterfs'
version          '0.1.0'

depends          'yum'
depends          'yum-centos'
